In [1]:
# ■ 기본적으로 필요한 패키지를 Import한다.
# ■ 현재 Code로 작성되고 있는지 반드시 확인한다.
import numpy as np
import pandas as pd
import tensorflow as tf
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

In [2]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
#Indexing
#배열 [0 1 2 3 4 5 6 7 8 9]
#순번  0 1 2 3 4 5
print(a[5])

5


In [4]:
#slicing
print(a[5:8])

[5 6 7]


In [8]:
print(a[-1])

9


In [15]:
print(a[-1:7])
print(a[-1:-5])
print(a[-1:5])
print(a[-7:-1])
print(a[7:-1])

[]
[]
[]
[  3   4 100 100 100   8]
[100   8]


In [16]:
#Slicing을 통해 범위 내 모든 숫자를 변경할 수 있다.
a[5:8] = 100
print(a)

[  0   1   2   3   4 100 100 100   8   9]


In [23]:
#indexing과 slicing의 차이
#indexing은 사용하고나면 항상 랭크(차원)가 감소한다.
# Ex) 2차원 배열 Indexing -> 1차원 배열
#     1차원 배열 Indexing -> 변수
#slicing은 사용해도 차원이 유지된다.
b = np.arange(1, 13)
print("#### Array B ####")
print(b)
print(b.shape)
print(b.ndim)
print("#### indexing ####")
idx = b[1]
print(idx, idx.shape, idx.ndim)
print("#### slicing ####")
slc = b[1:2]
print(slc, slc.shape, slc.ndim)
# idx = 2 / slc = [2]로
# 동일해보이는 숫자를 뽑아왔음에도 불구하고,
# idx의 경우 
# () -> shape이 없음
# 0 -> 0차원 (차원이 없음)
# slc의 경우
# (1,) -> shape 존재
# 1 -> 1차원

#### Array B ####
[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
1
#### indexing ####
2 () 0
#### slicing ####
[2] (1,) 1


In [30]:
#2차원 배열에서의 shape/ndim은 다음과 같다
b = b.reshape(3, 4)
print(b)
print(b.shape)
print(b.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
2


In [36]:
#2차원 배열 b에서 2개의 row를 추출한다.
row_r1 = b[1, :]
row_r2 = b[1:2, :]
print(row_r1, row_r1.shape, row_r1.ndim)
print(row_r2, row_r2.shape, row_r2.ndim)
# 5678로 내용물은 같으나, 
# indexing을 쓴 row_r1의 차원과 Slicing을 쓴 row_r2의 차원의 차이가 있음
row_r3 = b[1, 1]
print(row_r3, row_r3.shape, row_r3.ndim)
# row_r1에서 index을 한번 더 쓰면 차원이 0으로 한번 더 감소하는 것을 알 수 있다.

[5 6 7 8] (4,) 1
[[5 6 7 8]] (1, 4) 2
6 () 0


In [13]:
# tip
c = np.arange(1, 13)
#reshape : shape 옵션 값과 배열의 길이가 맞지 않으면 reshape 되지 않음
#c = np.arange(1, 14)
c = c.reshape(3, 4)
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
c = np.arange(24).reshape(2, 3, 4)
print(c)
print("\n")
print(c.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


(2, 3, 4)
