In [1]:
# ■ 기본적으로 필요한 패키지를 Import한다.
# ■ 현재 Code로 작성되고 있는지 반드시 확인한다.
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
# ■ 일반적인 Array와 ndArray는 다음과 같이 선언 가능하다.
L = [1, 2, 3]
A = np.array([1, 2, 3])
B = np.arange(10)

print(L)
print(A)
print(B)

[1, 2, 3]
[1 2 3]


In [3]:
# ■ 하나의 개체로서 살펴보면 다음과 같은 차이를 볼 수 있다.
L

[1, 2, 3]

In [4]:
A

array([1, 2, 3])

In [5]:
# ■ print로 각각의 item을 보면 별 다른 차이가 없다.
for item in L:
    print(item)

1
2
3


In [6]:
for item in A:
    print(item)

1
2
3


In [7]:
# ■ Append 함수 사용에 따른 차이
L.append(4)
print(L) # 오류 안남

[1, 2, 3, 4]


In [8]:
A = A.append(4)
print(A) # 오류남 (Append 지원 안함)


AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [12]:
# Append를 통해 ndArray에 인자를 추가하는 방법은 다음과 같다.
A = np.append(A, 4)
print(A)
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

[6 7 8 4]


In [9]:
# ■ 연산에 따른 차이 (덧셈)
L = L + [5]
print(L) # Array L의 후미에 5의 값을 갖는 인자가 추가되나,

[1, 2, 3, 4, 5]


In [10]:
print(A)
A = A + np.array([5])
print(A) #각각의 자리에 5만큼의 값이 더해진다.
#이러한 현상을 BroadCasting이라고 한다.

[1 2 3]
[6 7 8]


In [11]:
print(A)
A = A + np.array([5, 10])
print(A) # 에러가 난다

[6 7 8]


ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [13]:
print(A)
A = A + np.array([5, 10, 5, 10, 5])
print(A) # 자릿수가 맞아야 하는 것 같다.
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

[6 7 8 4]


ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [14]:
# ■ 연산에 따른 차이 (곱셈)
# python List - 모든 원소를 2배로 만들기
L = [1, 2, 3]
L2 = []
for item in L:
    L2.append(item * 2)
print(L2)

[2, 4, 6]


In [15]:
# ndArray - 모든 원소를 2배로 만들기
# ndArray에서는 연산이 조금 쉬워진다.
A = np.array(L)
A2 = A * 2
print(A2)


[2 4 6]


In [16]:
# List에 * N 연산을 할 경우, 해당 숫자만큼 인자가 늘어난다.
L = [1, 2, 3]
L2 = L * 2
print(L2)
L3 = L * 3
print(L3)
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

[1, 2, 3, 1, 2, 3]
[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [17]:
# ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
# ■ 배열
a = np.array([1, 2, 3])
print(a)
print(type(a), a.ndim, a.shape, a.dtype)

[1 2 3]
<class 'numpy.ndarray'> 1 (3,) int32


In [18]:
# 1 뒤에 .을 붙이는 경우, 소수로 인식된다.
a = np.array([1., 2, 3])
print(a)
print(type(a), a.ndim, a.shape, a.dtype) # float64가 된다

[1. 2. 3.]
<class 'numpy.ndarray'> 1 (3,) float64


In [19]:
# np ndArray를 생성하는 방법으로는,
# np.array와 np.asaray가 있는데,
a = np.array([1, 2, 3])
print(a)
b = np.asarray(a)
print(b)

b[0] = 9
print(a)
print(b)
# 일종의 View가 된다. (복사가 아니라, 같은 메모리를 바라보는 개체를 생성한다)

[1 2 3]
[1 2 3]
[9 2 3]
[9 2 3]


In [20]:
# b를 np.array로 선언한 후 같은 연산을 진행하면
a = np.array([1, 2, 3])
print(a)
b = np.array(a)
print(b)

b[0] = 9
print(a)
print(b)
# A가 변경되지 않는 것을 알 수 있다. 
# np.array로 생성시, 다른 메모리를 바라보는 새로운 개체가 copy되나,
# np.asarray로 생성시, 같은 메모리를 바라보는 개체를 생성한다.

[1 2 3]
[1 2 3]
[1 2 3]
[9 2 3]


In [21]:
# zeros
# 지정한 형태에 따라 0이 채워진 Matrix 생성
a = np.zeros((3, 4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
# ones
# 지정한 형태에 따라 1이 채워진 Matrix 생성
a = np.ones((3, 4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [25]:
# full
# 지정한 형태에 따라 지정한 숫자가 채워진 Matrix 생성
a = np.full((3, 4), 10)
print(a)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [33]:
# empty
# 지정한 형태에 따라 공간만생성
b = np.empty((3, 3))
print(b)

[[0.000e+000 0.000e+000 0.000e+000]
 [0.000e+000 0.000e+000 1.063e-320]
 [0.000e+000 0.000e+000 0.000e+000]]


In [35]:
# _like
# 선언된 개체의 형태에 따라 Matrix 생성
a = np.ones((3, 4))
b = np.zeros_like(a)
print(a)
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [37]:
a = np.full((3, 5), 22)
b = np.ones_like(a)
print(a)
print(b)

[[22 22 22 22 22]
 [22 22 22 22 22]
 [22 22 22 22 22]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [40]:
a = np.empty((3, 3))
b = np.full_like(a, 3)
print(a)
print(b)

[[0.000e+000 0.000e+000 0.000e+000]
 [0.000e+000 0.000e+000 1.063e-320]
 [0.000e+000 0.000e+000 0.000e+000]]
[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


In [45]:
a = np.zeros((3, 6))
b = np.empty_like(a)
print(a)
print(b)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [48]:
# eyes / identity
# 항등행렬
i = np.eye(3)
j = np.identity(3)
print(i)
print(j)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [66]:
# arange
# 옵션 : (시적점-이상, 종료점-미만, 방향성)
k = np.arange(10)
print(k)
k = np.arange(1, 21)
print(k)
k = np.arange(20, 0, -1)
print(k)

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


In [69]:
# 이게 왜 빈 행렬로 보이냐면
k = np.arange(10, -1)
print(k) 
# 방향성은 Default 양의 방향인데, 양의 방향으로 10부터 -1까지 존재하는 숫자가 없으므로
k = np.arange(10, -1, 1)
print(k) 
# 그러므로 이렇게 표기해주거나 (뱡향성을 올바르게)
k = np.arange(10, -1, -1)
print(k)
# 이렇게 표기해줘야한다. (시점과 종점을 올바르게)
K = np.arange(-1, 10)
print(k)

[]
[]
[10  9  8  7  6  5  4  3  2  1  0]
[10  9  8  7  6  5  4  3  2  1  0]


In [71]:
# rand
# Uniform Distribution 0~1 값을 모두가 똑같은 확률로 생성
l = np.random.rand(2, 2)
print(l)

[[0.50928914 0.30459488]
 [0.48165585 0.21343275]]


In [73]:
# randn
# Normal Distribution (표준 정규분포)에 따른 확률로 생성
m = np.random.randn(2, 2)
print(m)

[[ 0.49739903 -0.54311415]
 [ 0.58869984  0.48782192]]


In [76]:
#■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
a = np.array([1, 2, 3])
b = np.array([1, 2, 3], dtype = np.float64)
c = np.array([1, 2, 3], dtype = np.int32)

print(a.dtype, b.dtype, c.dtype)

int32 float64 int32


In [ ]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3], dtype = np.float64)
c = np.array([1, 2, 3], dtype = np.int32)